### ISSUE TITLE
Add chatbot analytics events

### ISSUE THREAD

**Issue by drorsnir** [kolzchut/react-app-KZChatbot#45]
רשימת Events שכתב אלי:
https://docs.google.com/document/d/1E-fWcNF_0gsZ3028EOIJj8E8UmnTg2v6TKUsjVEv784/edit#heading=h.ulr6fuyii0m3

```[tasklist]
### Tasks
- [x] https://github.com/kolzchut/react-app-KZChatbot/issues/46
- [x] Add Google Tag Manager handling for chatbot events in Staging
- [x] Add Google Tag Manager handling for chatbot events in Production
```
